/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// Importing Hamcrest library
import static org.hamcrest.MatcherAssert.assertThat; 
import static org.hamcrest.Matchers.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertThat("hamcrest: app should have a greeting",
           classUnderTest.getGreeting(), notNullValue());

    }

    @Test void greeetingIsHola() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hola mundo!");
    }
}
